name: CI/CD Fullstack to Azure

# 1. TRIGGERS (Cuando se ejecuta)
on:
  push:
    branches: ["**"] # Se ejecuta el CI y luego el CD al hacer merge
  workflow_dispatch:

env:
  # se ocupa solo 1 nombre porque se hace el deploy fullstack
  AZURE_WEBAPP_NAME: "MiApp-GitHub-Deploy"

  BACKEND_PACKAGE_PATH: "./backend"
  FRONTEND_PACKAGE_PATH: "./frontend"

  NODE_VERSION_BACKEND: "22.x"
  NODE_VERSION_FRONTEND: "22.x"

permissions:
  contents: read

jobs:
  # 1. BUILD BACKEND CI
  build-backend:
    runs-on: ubuntu-latest
    defaults:
      run:
        working-directory: ${{ env.BACKEND_PACKAGE_PATH }}
    steps:
      - uses: actions/checkout@v4

      - name: Set up Node.js for Backend
        uses: actions/setup-node@v4
        with:
          node-version: ${{ env.NODE_VERSION_BACKEND }}
          cache: "npm"
          cache-dependency-path: ${{ env.BACKEND_PACKAGE_PATH }}/package-lock.json

      - name: Instalar y Construir Backend
        env:
          DATABASE_URL: ${{ secrets.DATABASE_URL }}
        run: |
          npm ci
          npx prisma generate
          npm run build --if-present
          npm run test --if-present
          cp -r src/generated dist/src/

      - name: Subir artefacto del Backend
        uses: actions/upload-artifact@v4
        with:
          name: node-app-backend
          path: |
            ${{ env.BACKEND_PACKAGE_PATH }}/dist
            ${{ env.BACKEND_PACKAGE_PATH }}/prisma
            ${{ env.BACKEND_PACKAGE_PATH }}/prisma.config.ts
            ${{ env.BACKEND_PACKAGE_PATH }}/package.json
            ${{ env.BACKEND_PACKAGE_PATH }}/package-lock.json
            ${{ env.BACKEND_PACKAGE_PATH }}/node_modules

  # 2. BUILD FRONTEND CI
  build-frontend:
    runs-on: ubuntu-latest
    defaults:
      run:
        working-directory: ${{ env.FRONTEND_PACKAGE_PATH }}
    steps:
      - uses: actions/checkout@v4

      - name: Set up Node.js for Frontend
        uses: actions/setup-node@v4
        with:
          node-version: ${{ env.NODE_VERSION_FRONTEND }}
          cache: "npm"
          cache-dependency-path: ${{ env.FRONTEND_PACKAGE_PATH }}/package-lock.json

      - name: Instalar y Construir Frontend
        run: |
          npm ci
          npm run build --if-present
          npm run test --if-present

      - name: Subir artefacto del Frontend
        uses: actions/upload-artifact@v4
        with:
          name: node-app-frontend
          path: ${{ env.FRONTEND_PACKAGE_PATH }}/dist # solo se sube la carpeta 'dist' del frontend construido

  # 3. DEPLOY FULLSTACK CD (front y back)
  deploy-fullstack:
    if: github.event_name == 'push'
    runs-on: ubuntu-latest
    needs: [build-backend, build-frontend]

    environment:
      name: production

    # Permisos requeridos por OIDC para iniciar sesion sin contrasenas
    permissions:
      id-token: write
      contents: read

    steps:
      - name: Descargar artefacto del Backend
        uses: actions/download-artifact@v4
        with:
          name: node-app-backend
          path: ./app-final

      - name: Descargar artefacto del Frontend
        uses: actions/download-artifact@v4
        with:
          name: node-app-frontend
          path: ./app-final/client

      - name: Iniciar sesion en Azure (OIDC)
        uses: azure/login@v2
        with:
          client-id: ${{ secrets.AZURE_CLIENT_ID }}
          tenant-id: ${{ secrets.AZURE_TENANT_ID }}
          subscription-id: ${{ secrets.AZURE_SUBSCRIPTION_ID }}

      - name: Desplegar Fullstack a Azure WebApp
        id: deploy-to-webapp
        uses: azure/webapps-deploy@v2
        with:
          app-name: ${{ env.AZURE_WEBAPP_NAME }} # Solo usa el unico nombre
          package: ./app-final # Despliega la carpeta unificada
