# This workflow will do a clean installation of node dependencies, cache/restore them, build the source code and run tests across different versions of node
# For more information see: https://docs.github.com/en/actions/automating-builds-and-tests/building-and-testing-nodejs
name: CI Pipeline MakerBox

on:
  push:
    branches: [ "main" ]
  pull_request:
    branches: [ "main" ]
jobs:
  build-backend:
    name: Backend Check
    runs-on: ubuntu-latest
    defaults:
      run:
        working-directory: ./backend

    steps:
      - name: descargar codigo
        uses: actions/checkout@v4

      - name: Configurar Node.js 
        uses: actions/setup-node@v4
        with:
          node-version: '20'
          cache: 'npm'
          cache-dependency-path: backend/package-lock.json

      - name: Instalar dependencias
        run: npm ci

      - name: Ejecutar Linter
        run: npm run lint

      - name: Ejecutar pruebas y cobertura
        run: npm run test:cov

      - name: Subir Reporte, Backend
        uses: actions/upload-artifact@v4
        if: always()
        with:
          name: coverage-report-backend
          path: backend/coverage/

  build-frontend:
    name: Frontend Check
    runs-on: ubuntu-latest
    defaults:
      run:
        working-directory: ./frontend

    steps:
      - name: Descargar codigo
        uses: actions/checkout@v4

      - name: Configurar Node.js 
        uses: actions/setup-node@v4
        with:
          node-version: '20'
          cache: 'npm'
          cache-dependency-path: frontend/package-lock.json

      - name: Instalar dependencias
        run: npm ci

      - name: Ejecutar linter
        run: npm run lint

      - name: Ejecutar pruebas y cobertura
        run: npm run test:cov

      - name: Subir reporte de Frontend
        uses: actions/upload-artifact@v4
        if: always()
        with:
          name: coverage-report-frontend
          path: frontend/coverage/
